### ISSUE TITLE
Agent `v0.71.0` Release Notes

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1921]
Intended as a parking area for release notes.

- [ ] ~~Layout the tech-preview for the new "pbench" command~~
- [x] Layout the tech-preview for the new HTTP PUT method of posting tar balls
- [x] Latent support for the new pbench-server PUT API
- [ ] ~~Tool Meister now collects system information in addition to tool data~~
- [ ] ~~Addition of the `pbench-move-results --controller=<name>` option~~
- [x] Removal of deprecated `pbench-fio --remote-only` (#2543)
- [x] Change to check command versions instead of RPM version for `pbench-fio` and `pbench-uperf` (#2528)
- [x] Require the `--user` option for `pbench-move-results` (PR #2544)

**Comment by portante** [comment]
The Alpha release notes will be created via PR #2792.

**Comment by portante** [comment]
All of the items listed in the description have been added to PR #2792.

**Comment by portante** [comment]
Release notes finalized in PR #2792.
