### ISSUE TITLE
Bumps in the road to installing a Server in a green field

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2422]
Today, Dave, Nikhil, and I [fought our way](https://drive.google.com/file/d/1oPlvOGFG_vvGZQ1Yt3thHI9Kt7dcic1C/view) from a brand new VM to a successfully installed Pbench Server (to which we uploaded results which we were able to view in a Dashboard instance).  It was not a smooth process.  And, at the moment, it is not mechanically/automatically reproducible, although it is close.  I'm using this issue to record the bumps we hit along that road.  At the bottom is a summary of work items (although, if you read the list of bumps, you may find additional ones).  Dave has resolved some of the problems in #2423; some problems may require a more significant effort to smooth out.

NOTE: This is useful to have recorded in one place, but it ought to be a Jira story (@pravins) with a series of more focused independent *tasks* as we define them which can be reflected back into GitHub during planning.

## The bumps in the Server installation road

- [ ] Use the correct Ansible playbook....
- [ ] Ensure that the system has the correct RPM PGP key for the EPEL (and other) repos that we pull from. (Can this be automated in Ansible?)
- [ ] Enable the COPR repo selected for the Pbench install. (Ansible roles use `pbench_repo_url_prefix`, but can the `dnf`/`yum` "enable" operation be automated to enable "green field" installs or is some manual pre-install setup inevitable?)
- [ ] `firewalld` needs to be installed _and_ started; or role needs to be smart enough to skip firewall configuration if not installed.
- [x] We initially couldn't start the server because Click was not installed.  It was not listed as a direct dependency of the Server.  (We discovered later that it is normally installed as a dependency of Flask, but, because of another issue, the installations were not completing, so it wasn't being installed.)   We added it to the `requirements.txt` for the Server.
- [x] While investigating the missing Click installation, we found an error in the RPM installation "post" step indicating that `psycopg2-binary` wouldn't install via `pip3`.  This shouldn't have been an actual problem because `psycopg2` is already installed via RPM dependency.  We removed `psycopg2-binary` from the `requirements.txt`.  The weird thing is that, apparently, the ansible script proceeded despite the fact that the `pip3` installs aborted in the middle!
- [x] Resolving the `psycopg2` issue allowed the installation proceed, but it ran extremely slowly because `pip3` was downloading every possibly-compatible version of several packages in an effort to find the best compatible version, and it was taking forever.  So, we added an explicit version requirement for `alembic`, and we added explicit requirements (with versions) for `aniso8601`, `sqlalchemy`, and `sqlalchemy_utils`.  (This improved this dramatically...and we _assume_ it worked....)
- [x] We added `/opt/pbench-server/lib/python3.6/site-packages/` and `/opt/pbench-server/lib64/python3.6/site-packages/` to the `PYTHONPATH` definition in the `pbench_server.service` file.  Note the Python version dependency!
- [ ] We added `/opt/pbench-server/bin` to the `PATH` in the `pbench_server.service` file.
- [x] The `PYTHONPATH` definition in the crontab needed to be similarly updated.
- [x] We had to down-grade the Python `elasticsearch` package from `7.14.0` to `7.13.1`.
- [ ] The `PUT` API is putting the uploaded files in `/src/pbench/pbench-move-results-receive/fs-version-002` where they can be found by the prep-shim, forming a race condition to a conflict.  We removed the prep-shim from the crontab, since it shouldn't be needed or used in 0.71+ (and, in fact, it caused a problem!).

## Work items

- [x] We need to have Ansible determine the correct `PYTHONPATH` (e.g.) by looking at the results of the `pip3` install into `/opt/pbench-server/lib/` to find the `python3.X/site-packages` path component, and save the result in a variable for use in generating the `PYTHONPATH` in the service file, crontab, et al.
- [x] Get the `PYTHONPATH` right for service, crontab, and any Ansible roles which use Pbench commands on the installation machine.
- [ ] Determine why the failure in the package installation (error in `%post`) was silent and didn't fail the playbook.
- [ ] The Ansible script should detect whether `firewalld` is installed and started; it should either install it if necessary and start it if necessary, or skip configuring the firewall if it's not there.
- [ ] Use RPM dependencies instead of relying on `pip3`/`requirements.txt` for providing package dependencies.  (E.g., the container builds for Jenkins do this, and perhaps the knowledge will transfer.)
- [ ] Wherever practical, peg dependent requirements to specific versions or version ranges.
- [ ] The `PUT` API should be putting the uploads into a temporary directory or some other place rather than re-using the ssh-upload location.

**Comment by portante** [comment]
We are taking a different approach from using Ansible which was a big part of the recorded effort above, and we have removed our use of Ansible on the server side (see PR #2936).
